M48
; DRILL file {KiCad 7.0.10} date Thu Mar  7 14:05:51 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-07T14:05:51+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0394
%
G90
G05
T1
X5.6594Y-3.1902
X5.6594Y-3.4177
T2
X6.8583Y-3.5327
X6.9764Y-3.5327
M30
